name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"   # se ejecuta todos los d√≠as a medianoche
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Generate Snake
        uses: Platane/snk@v3
        with:
          github_user_name: medusahra
          outputs: |
            ./output/github-contribution-grid-snake.svg
            ./output/github-contribution-grid-snake-dark.svg

      - name: Commit files
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Generate Snake Animation"
          file_pattern: output/*

      - name: Push changes
        run: git push
